# Generated by Django 5.1.1 on 2024-10-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcial_soft2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
